--[[  Generated by FAF Map Editor                                              ]]--
-- Table of which resources belong to which player, it is sorted in such a way that the first line
-- corresponds to player one, the second to player 2 and so on...

maxPlayerOnMap = 8




-- Line number is 10 + armynumber for the mexes in the table
spwnMexArmy = {		{12,14,16,18,20,22},
                    {37,39,41,43,45,47},
                    {13,15,17,19,21,23},
                    {25,27,29,31,33,35},
                    {36,38,40,42,44,46},
                    {24,26,28,30,32,34},
                    {00,02,04,06,08,10},
                    {01,03,05,07,09,11},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}



-- Line number is 30 + armynumber for the hydros in the table
spwnHydroArmy = {	{02},
                    {03},
                    {04},
                    {05},
                    {06},
                    {07},
                    {00},
                    {01},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {},
                    {}}


-- RESOURCE SCALING OPTIONS
-- exampleMexes = {{1,2},{3,4},{5,6}},        -- exampleMexes = {{1,2}}
-- exampleMexes = {{a},{b},{c}},              -- exampleMexes = {{a}}
-- option key=1 : removes a+b+c               -- option key=1 : removes a
-- option key=2 : spawn a, removes b+c        -- option key=2 : spawns a
-- option key=3 : spawn a+b, removes c
-- option key=4 : spawn a+b+c

extraHydros = {{}}

extraMexes = {{}}

middleMexes = {{},{},{}}

sideMexes = {{},{},{}}

underwaterMexes = {{},{},{}}

islandMexes = {{},{},{}}

expansionMexes = {{},{},{}}

coreMexes = {{}}

extraBaseMexes = {{}}

topSideMexes = {{},{},{}}

bottomSideMexes = {{},{},{}}

forwardCrazyrushMexes = {}

crazyrushOneMexes = {}

